---
#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

#MySQL Settings
mysql_root_password: "root"
mysql_db: "wordpress"
mysql_user: "wordpressuser"
mysql_password: "1234"

#HTTP Settings
http_host: "ip-172-31-30-222"
http_conf: "wordpress.conf"
http_port: "80"
